config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin_dashboard', as: 'rails_admin'
  # ==============================================================================================
  # Static Pages
  # ==============================================================================================
  root 'pages#home'

  # Header
  get '/team', to: 'pages#team', as: 'team'
  get '/press', to: 'pages#press', as: 'press'
  get '/product', to: 'pages#product', as: 'product'
  get '/kickstarter', to: 'pages#kickstarter', as: 'kickstarter'

  # Footer
  get '/faq', to: 'pages#faq', as: 'faq'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/tnc', to: 'pages#tnc', as: 'tnc'

  # Soma
  get '/share', to: 'pages#share', as: 'share'

  post :contact_us, to: 'contacts#send_contact_form'
 
  # ==============================================================================================
  # Flywheel (Blog)
  # ==============================================================================================
  get '/blog' => redirect("http://www.hyveplus.com/blog/") 

  # ==============================================================================================
  # Resources
  # ==============================================================================================

  resources :users, only: [:new, :create] 
  resources :password_resets, only: [:new, :create, :edit, :update]

  # ==============================================================================================
  # User Sessions/Login/Logout
  # ==============================================================================================
  resources :user_sessions, only: [:create]
  get 'login', to: 'user_sessions#new', as: 'login'
  post 'logout', to: 'user_sessions#destroy', as: 'logout'

  # ==============================================================================================
  # Mailchimp Subscription
  # ==============================================================================================
  post :subscribe_early_adopters, to: 'mailings#sub_adopters'

  # ==============================================================================================
  # Sorcery/Omniauth
  # ==============================================================================================
  post 'oauth/callback', to: 'oauth#callback'
  get 'oauth/callback', to: 'oauth#callback' #for use with Facebook
  get 'oauth/:provider', to: 'oauth#oauth', as: :auth_at_provider

  # ==============================================================================================
  # MY namespace
  # ==============================================================================================
  namespace :my do
    resources :hyves, only: [:update]
    resource :account, only: [:show] do
      patch :update_profile, on: :member
      patch :update_password, on: :member 
      #patch "update_hyve/:uuid", to: 'accounts#update_hyve', as: :update_hyve 
    end
  end
  
  # ==============================================================================================
  # Admin namespace
  # ==============================================================================================
  namespace :admin do
    resources :users, except: [:new, :create]
    resources :hyves, except: [:new, :create]
  end

  # ==============================================================================================
  # API for iOS mobile
  # ==============================================================================================
  namespace :api do
    namespace :v1 do
      resource :account, only: [:show, :update]
      resources :hyves, except: [:new, :edit]
      resources :user_sessions, only: [:create, :destroy]
      post :register, to: 'user_sessions#register'
    end
  end


  # ==============================================================================================
  # API for Android mobile
  # ==============================================================================================
  #namespace :api do
    #namespace :v1 do
      #resource :account, only: [:show, :update]
      #resources :hyves, except: [:new, :edit]
      #resources :user_sessions, only: [:create, :destroy]
      #post :register, to: 'user_sessions#register'
    #end
  #end
end

app/views/layouts/login_modal/_user_forgot_password.html.slim
#user-forgot-password.container.hidden
  .row.padded-btm-1
    .col-md-12.col-lg-12
      h3.no-margin Enter your email address and we'll get you back on track
  .row.padded-top-1.padded-btm-2
    = form_tag password_resets_path, method: :post do
      .text-centered
        = email_field_tag :email, nil, placeholder: "Email Address", class: "form-login-modal"
      .text-centered
        = submit_tag "Reset my password", class: "btn btn-orange"
  .row.text-centered.padded-top-4
    p Back to <a href="#user-login", class="user-login-link orange-link">Login</a>

app/views/layouts/login_modal/_user_login.html.slim
#user-login.container
  .row.row-eq-height.padded-btm-1
    .col-md-6.col-lg-6.vertical-align.left-align
      h3.no-margin User Login
    .col-md-6.col-lg-6.vertical-align.right-align
      = link_to "Forgot Password?", "#user-forgot-password", class: "user-forgot-password-link text-right"

  .row.padded-btm-2
    = form_for :user_sessions, url: user_sessions_path , method: :post do |f|
      .text-centered = f.text_field :email, placeholder: 'email@hyve.com', required: true, class: "form-login-modal"
      .text-centered = f.password_field :password, placeholder: 'Password', required: true, class: "form-login-modal"
      .text-centered = f.submit "Login", class: "btn btn-login"

  .row.padded-top-2.padded-btm-1
    /.text-centered = link_to raw("<i class='fa fa-facebook-f facebook-social-icon'></i>CONNECT WITH FACEBOOK"), auth_at_provider_path(provider: :facebook), class: "btn btn-login-facebook"
    .text-centered = link_to raw("<i class='fa fa-google-plus google-social-icon'></i>CONNECT WITH GOOGLE"), auth_at_provider_path(provider: :google), class: "btn btn-login-google"

  .row.text-centered.padded-top-1
    p Not a member yet? Please feel fee to <a href="#user-signup" class="user-signup-link orange-link">Sign Up</a>

app/views/layouts/login_modal/_user_signup.html.slim
#user-signup.container.hidden
  .row.row-eq-height.padded-btm-1
    .col-md-5.col-lg-5.vertical-align.left-align
      h3.no-margin Sign Up
    .col-md-7.col-lg-7.vertical-align.right-align
      p.no-margin Already have an account? <a href="#user-login" class="user-login-link orange-link">Login</a>

  .row
    = form_for :user, url: users_path , method: :post do |f|
      .text-centered
        = f.text_field :email, placeholder: 'Email Address', required: true, class: "form-login-modal"
      .text-centered 
        = f.text_field :first_name, placeholder: "First Name", required: true, class: "form-login-modal"
      .text-centered 
        = f.text_field :last_name, placeholder: "Last Name", required: true, class: "form-login-modal"
      .text-centered 
        = f.password_field :password, placeholder: 'Password', required: true, class: "form-login-modal"
      .text-centered 
        = f.password_field :password_confirmation, placeholder: 'Repeat Password', required: true, class: "form-login-modal"
      .text-centered 
        = f.submit "Sign Up", class: 'btn btn-orange'

  .row.text-centered.padded-top-1
    p By click "Sign Up", you agree to HYVE's <a href="/tnc", class="blue-link">Terms and Conditions</a>