config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin_dashboard', as: 'rails_admin'
  # ==============================================================================================
  # Static Pages
  # ==============================================================================================
  root 'pages#home'

  # Header
  get '/team', to: 'pages#team', as: 'team'
  get '/press', to: 'pages#press', as: 'press'
  get '/product', to: 'pages#product', as: 'product'
  get '/kickstarter', to: 'pages#kickstarter', as: 'kickstarter'

  # Footer
  get '/faq', to: 'pages#faq', as: 'faq'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/tnc', to: 'pages#tnc', as: 'tnc'

  # Soma
  get '/share', to: 'pages#share', as: 'share'

  post :contact_us, to: 'contacts#send_contact_form'
 
  # ==============================================================================================
  # Flywheel (Blog)
  # ==============================================================================================
  get '/blog' => redirect("http://www.hyveplus.com/blog/") 

  # ==============================================================================================
  # Resources
  # ==============================================================================================

  resources :users, only: [:new, :create] 
  resources :password_resets, only: [:new, :create, :edit, :update]

  # ==============================================================================================
  # User Sessions/Login/Logout
  # ==============================================================================================
  resources :user_sessions, only: [:create]
  get 'login', to: 'user_sessions#new', as: 'login'
  post 'logout', to: 'user_sessions#destroy', as: 'logout'

  # ==============================================================================================
  # Mailchimp Subscription
  # ==============================================================================================
  post :subscribe_early_adopters, to: 'mailings#sub_adopters'

  # ==============================================================================================
  # Sorcery/Omniauth
  # ==============================================================================================
  post 'oauth/callback', to: 'oauth#callback'
  get 'oauth/callback', to: 'oauth#callback' #for use with Facebook
  get 'oauth/:provider', to: 'oauth#oauth', as: :auth_at_provider

  # ==============================================================================================
  # MY namespace
  # ==============================================================================================
  namespace :my do
    resources :hyves, only: [:update]
    resource :account, only: [:show] do
      patch :update_profile, on: :member
      patch :update_password, on: :member 
      #patch "update_hyve/:uuid", to: 'accounts#update_hyve', as: :update_hyve 
    end
  end
  
  # ==============================================================================================
  # Admin namespace
  # ==============================================================================================
  namespace :admin do
    resources :users, except: [:new, :create]
    resources :hyves, except: [:new, :create]
  end

  # ==============================================================================================
  # API for iOS mobile
  # ==============================================================================================
  namespace :api do
    namespace :v1 do
      resource :account, only: [:show, :update]
      resources :hyves, except: [:new, :edit]
      resources :user_sessions, only: [:create, :destroy]
      post :register, to: 'user_sessions#register'
    end
  end


  # ==============================================================================================
  # API for Android mobile
  # ==============================================================================================
  #namespace :api do
    #namespace :v1 do
      #resource :account, only: [:show, :update]
      #resources :hyves, except: [:new, :edit]
      #resources :user_sessions, only: [:create, :destroy]
      #post :register, to: 'user_sessions#register'
    #end
  #end
end

app/models/hyve.rb
class Hyve < ActiveRecord::Base

  #Associations
	belongs_to :user

  #Validations
  validates_presence_of :name

  validates_format_of :distance, with: /\A(1|2|4|8|16)\z/

  validates_inclusion_of :proximity, in: ["out of range", "close by"], allow_blank: true

  validates_presence_of :uuid
  validates_uniqueness_of :uuid, case_sensitive: false
  validates_format_of :uuid, with: /\A[\w -]+\z/, message: "can only have alphanumeric or - characters"
  

  #Carrierwave
  mount_uploader :image, HyveImageUploader

  # Friendly ID
  def to_param
    uuid
  end

end

app/controllers/admin/hyves_controller.rb
class Admin::HyvesController < Admin::AdminsController
  before_action :set_hyve, except: [:index]

  def index
    @hyves = Hyve.all.order(:id)
    authorize @hyves
  end

  def show
  end

  def edit
  end

  def update
    if @hyve.update(hyve_params)
      redirect_to admin_hyve_path(@hyve)
    else
      render :edit
    end
  end

  def destroy
    @hyve.destroy
    redirect_to admin_hyves_path, notice: "#{@hyve.name}-#{@hyve.user.email} successfully deleted from the database."
  end

  private

  def set_hyve
    @hyve = Hyve.find_by_uuid(params[:id])
    authorize @hyve
  end

  def hyve_params
    params.require(:hyve).permit(:name, :uuid, :distance)
  end
end

app/controllers/api/v1/hyves_controller.rb
class Api::V1::HyvesController < Api::ApiController
  before_action :set_hyve, only: [:show, :update, :destroy]

  def index
    @hyves = @user.hyves.sort_by { |hyve| hyve.name }
    render json: @hyves
  end

  def show
    render json: @hyve
  end

  def create
    @hyve = @user.hyves.build(hyve_params)
    @hyve.remote_image_url = hyve_params[:image] if present?
    if @hyve.save
      render json: @hyve
    else
      render json: { errors: @hyve.errors }
    end
  end

  def update
    @hyve.remote_image_url = hyve_params[:image] if present?
    if @hyve.update(hyve_params)
      render json: @hyve
    else
      render json: @hyve.errors
    end
  end

  def destroy
    @hyve.destroy
    render json: { status: "Hyve destroyed" }
  end

  private
  
  def set_hyve
    @hyve = Hyve.find_by_uuid(params[:id]) || NilHyve.new
  end

  def hyve_params
    params.require(:hyve).permit(:name, :distance, :uuid, :image, :proximity)
  end
end

class NilHyve
  attr_accessor :error

  def initialize
    @error = "UUID error, no hyve found."
  end
end

app/controllers/hyves_controller.rb
class HyvesController < ApplicationController
  before_action :set_user
  before_action :set_hyve, except: [:index]

  def index
    @hyves = @user.hyves.all 
  end

  def show
  end

  def edit
  end

  def update
    if @hyve.update(hyve_params)
      redirect_to hyve_path, notice: "Your hyve was successfully updated."
    else
      render :edit 
    end
  end
  
  def destroy
  end

  private
    def set_user
      @user = current_user
    end

    def set_hyve
      @hyve = Hyve.find(params[:id])
    end

    def hyve_params
      params.require(:hyve).permit(:name, :uuid, :distance, :status)
    end
end

app/controllers/my/hyves_controller.rb
class My::HyvesController < My::BaseController
  before_action :set_hyve

  def update
    if @hyve.update(hyve_params)
      redirect_to my_account_path, notice: "Your hyve was successfully updated."
    else
      flash[:error] = @hyve.errors.full_messages
      redirect_to my_account_path
    end
  end

  private

  def set_hyve
    # Friendly ID implementation
    @hyve = Hyve.find_by(uuid: params[:id])
  end

  def hyve_params
    params.require(:hyve).permit(:name, :distance, :image)
  end
end

app/helpers/hyves_helper.rb
module HyvesHelper
end

app/views/admin/hyves/edit.html.slim
.container
  = form_for @hyve, url: admin_hyve_path, method: :patch do |f|
    - if @hyve.errors.any?
      #error_explanation
        h2 = "#{pluralize(@hyve.errors.count, "error")} prohibited this user from being saved:"
        ul
          - @hyve.errors.full_messages.each do |message|
            li = message
    table
      col width="200"
      col width="200"
      tr
        td
          = f.label :name
        td
          = f.text_field :name, class: 'full-width-input'
      tr
        td
          = f.label :uuid
        td
          = f.text_field :uuid, class: 'full-width-input'
      tr
        td
          = f.label :distance
        td
          = f.text_field :distance, class: 'full-width-input'
      tr
        td
          = f.label :avatar
        td
          = f.file_field :avatar, type: 'file'
    = f.submit "Update Profile", class: "btn btn-primary"

  br
  = link_to "Back to Show Hyve Page", admin_hyve_path, class: "btn btn-info"

app/views/admin/hyves/index.html.slim
#admin-hyves.container
  h1 All Hyves
  table
    col width="30"
    col width="150"
    col width="150"
    col width="80"
    col width="200"
    col width="200"
    col width="200"
    col width="100"
    col width="100"
    col width="100"
    thead
      tr
        th rowspan="2" ID
        th rowspan="2" Name
        th rowspan="2" UUID
        th rowspan="2" Distance
        th colspan="3" Hyve User Details 
        th colspan="3" rowspan="2" Action
      tr
        th Username
        th First Name
        th Last Name
    tbody
    - @hyves.each do |hyve|
      tr
        td = hyve.id
        td = hyve.name
        td = hyve.uuid
        td = hyve.distance
        td = hyve.user.username
        td = hyve.user.first_name
        td = hyve.user.last_name
        td = link_to "Show", admin_hyve_path(hyve)
        td = link_to "Edit", edit_admin_hyve_path(hyve)
        td = link_to "Delete", admin_hyve_path(hyve), method: :delete, data: { confirm: "Are you would like to delete #{hyve.name} #{hyve.user.email}?" }

app/views/admin/hyves/show.html.slim
.container
  table
    col width='150'
    tr
      td
        strong Name
      td
        = @hyve.name
    tr
      td
        strong UUID
      td
        = @hyve.uuid
    tr
      td
        strong Distance
      td
        = @hyve.distance
    tr
      td
        p
    tr
      td
        strong User's Details
    tr
      td
        strong Email
      td = @hyve.user.email
    tr
      td
        strong Username
      td = @hyve.user.username
    tr
      td
        strong First Name
      td = @hyve.user.first_name
    tr
      td
        strong Last Name
      td = @hyve.user.last_name

  - if @hyve.image_url.nil?
    p No Avatar
  - else
    = image_tag "#{@hyve.image}", class: "margin-top-2 margin-btm-2"

  p
    = link_to "Edit Hyve", edit_admin_hyve_path, class: "btn btn-primary"
  p 
    = link_to "Delete", admin_hyve_path(@hyve), method: :delete, data: { confirm: "Are you would like to delete #{@hyve.name}-#{@hyve.user.email}?" }, class: "btn btn-danger"
  p
    = link_to 'Back to Hyves Index', admin_hyves_path, class: "btn btn-default"