config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin_dashboard', as: 'rails_admin'
  # ==============================================================================================
  # Static Pages
  # ==============================================================================================
  root 'pages#home'

  # Header
  get '/team', to: 'pages#team', as: 'team'
  get '/press', to: 'pages#press', as: 'press'
  get '/product', to: 'pages#product', as: 'product'
  get '/kickstarter', to: 'pages#kickstarter', as: 'kickstarter'

  # Footer
  get '/faq', to: 'pages#faq', as: 'faq'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/tnc', to: 'pages#tnc', as: 'tnc'

  # Soma
  get '/share', to: 'pages#share', as: 'share'

  post :contact_us, to: 'contacts#send_contact_form'
 
  # ==============================================================================================
  # Flywheel (Blog)
  # ==============================================================================================
  get '/blog' => redirect("http://www.hyveplus.com/blog/") 

  # ==============================================================================================
  # Resources
  # ==============================================================================================

  resources :users, only: [:new, :create] 
  resources :password_resets, only: [:new, :create, :edit, :update]

  # ==============================================================================================
  # User Sessions/Login/Logout
  # ==============================================================================================
  resources :user_sessions, only: [:create]
  get 'login', to: 'user_sessions#new', as: 'login'
  post 'logout', to: 'user_sessions#destroy', as: 'logout'

  # ==============================================================================================
  # Mailchimp Subscription
  # ==============================================================================================
  post :subscribe_early_adopters, to: 'mailings#sub_adopters'

  # ==============================================================================================
  # Sorcery/Omniauth
  # ==============================================================================================
  post 'oauth/callback', to: 'oauth#callback'
  get 'oauth/callback', to: 'oauth#callback' #for use with Facebook
  get 'oauth/:provider', to: 'oauth#oauth', as: :auth_at_provider

  # ==============================================================================================
  # MY namespace
  # ==============================================================================================
  namespace :my do
    resources :hyves, only: [:update]
    resource :account, only: [:show] do
      patch :update_profile, on: :member
      patch :update_password, on: :member 
      #patch "update_hyve/:uuid", to: 'accounts#update_hyve', as: :update_hyve 
    end
  end
  
  # ==============================================================================================
  # Admin namespace
  # ==============================================================================================
  namespace :admin do
    resources :users, except: [:new, :create]
    resources :hyves, except: [:new, :create]
  end

  # ==============================================================================================
  # API for iOS mobile
  # ==============================================================================================
  namespace :api do
    namespace :v1 do
      resource :account, only: [:show, :update]
      resources :hyves, except: [:new, :edit]
      resources :user_sessions, only: [:create, :destroy]
      post :register, to: 'user_sessions#register'
    end
  end


  # ==============================================================================================
  # API for Android mobile
  # ==============================================================================================
  #namespace :api do
    #namespace :v1 do
      #resource :account, only: [:show, :update]
      #resources :hyves, except: [:new, :edit]
      #resources :user_sessions, only: [:create, :destroy]
      #post :register, to: 'user_sessions#register'
    #end
  #end
end

app/controllers/api/v1/accounts_controller.rb
class Api::V1::AccountsController < Api::ApiController
  def show
    render json: @user, serializer: UserSerializer
  end

  def update
    @user.remote_avatar_url = user_params[:avatar] if present?
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :first_name, :last_name, :avatar, :password, :password_confirmation)
  end

end

app/controllers/my/accounts_controller.rb
class My::AccountsController < My::BaseController
  before_action :set_user, :set_hyves
  before_action :set_action, only: [:update_profile]

  def show
  end

  def update_profile
    @initial_subscription = @user.subscription

    # Calls Mailchimp API only if subscription status changes
    if @initial_subscription != @updated_subscription
      create_nice_sentence(@action)
      begin
        response = Mailings::MailChimpService.new(@email).send(@action)
        @user.update(subscription: @updated_subscription) if @user
        flash[:success] = "#{@email} #{@combine} newsletter successfully"
      rescue Gibbon::MailChimpError => e
        flash[:error] = e.message
      end
    end
 
    update(@user, profile_params, "profile")
  end

  def update_password
    update(@user, password_params, "password")
  end

  private

  def set_user
    @user = current_user
  end

  def set_hyves
    @hyves = current_user.hyves
  end

  #def set_hyve
    ## Friendly ID implementation
    #@hyve = Hyve.find_by(uuid: params[:uuid])
  #end

  def set_action
    @email = params.fetch(:user)[:email]
    if params.fetch(:user)[:subscription] == "1"
      @action = "subscribed_to_users"
      @updated_subscription = true
    else
      @action = "unsubscribed_from_users"
      @updated_subscription = false
    end
  end

  def create_nice_sentence(action)
    @split = action.gsub(/_/, " ").split
    @uppercase = @split.drop(2).collect { |s| s.capitalize }
    @combine = "has " + @split[0] + " " + @split[1] + " " + @uppercase.join
  end

  def update(object, parameters, text)
    if object.update(parameters)
      redirect_to my_account_path, notice: "Your #{text} was successfully updated."
    else
      flash[:error] = object.errors.full_messages
      redirect_to my_account_path
    end
  end

  def profile_params
    params.require(:user).permit(:email, :username, :first_name, :last_name, :avatar, :username, :subscription)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/my/base_controller.rb
class My::BaseController < ApplicationController
  before_action :require_login
end

app/controllers/my/hyves_controller.rb
class My::HyvesController < My::BaseController
  before_action :set_hyve

  def update
    if @hyve.update(hyve_params)
      redirect_to my_account_path, notice: "Your hyve was successfully updated."
    else
      flash[:error] = @hyve.errors.full_messages
      redirect_to my_account_path
    end
  end

  private

  def set_hyve
    # Friendly ID implementation
    @hyve = Hyve.find_by(uuid: params[:id])
  end

  def hyve_params
    params.require(:hyve).permit(:name, :distance, :image)
  end
end

app/views/my/accounts/_edit_my_hyve_info.html.slim
.container.hidden id="edit-my-hyve-#{hyve.id}-info"
  = form_for hyve, url: my_hyve_path(hyve), method: :patch do |f|
    .row.row-eq-height
      .col-xs-12.col-sm-3.col-md-3.col-lg-3.vertical-align.center-align
        .row
          .col-xs-12.col-sm-12.col-md-12.col-lg-12.text-centered
            - if hyve.image.blank?
              = image_tag "my_account/default.png", class: "my-hyve-image-large"
            - else
              = image_tag "#{hyve.image}", class: "my-hyve-image-large"
          .col-xs-12.col-sm-12.col-md-12.col-lg-12.margin-top-2
            = f.file_field :image, accept: "image/png, image/gif, image/jpeg", style: "display: inline-flex"
      .col-xs-12.col-sm-7.col-md-7.col-lg-7.text-left.vertical-align
        table#edit-hyve-info-details
          col width="150"
          col width="30"
          col width="50"
          col width="350"
          tr
            td colspan="4"
              = f.text_field :name, class: "form-my-hyve"
          tr
            td
              = f.label :distance
            td
              | :
            td
              = f.select :distance, %w[1 2 4 8 16]
            td
              label.no-margin metres
          tr
            td
              label Proximity
            td
              | :
            td.orange colspan="2"
              - if hyve.proximity
                = hyve.proximity
              - else
                p.no-margin Unknown
          tr
            td
              label Registered Date
            td
              | :
            td colspan="2"
              = hyve.created_at
          tr
            td
              label Last Connected
            td
              | :
            td colspan="2"
              = hyve.updated_at
          tr
            td
              label UUID
            td
              | :
            td colspan="2"
              = hyve.uuid
      .col-xs-2.col-sm-2.col-md-2.col-lg-2.bottom-align.right-align
        = f.submit "Save", class: "btn btn-my-account-update"

app/views/my/accounts/_edit_my_user_info.html.slim
#edit-my-user-info.container-fluid.hidden
  = render "my/accounts/edit_user_info/personal_info"
  = render "my/accounts/edit_user_info/password"

app/views/my/accounts/_my_hyve_info.html.slim
#my-hyve-info.container
  #hyves-accordion.panel-group aria-multiselectable="true" role="tablist" 
    - @hyves.each do |hyve|
      .panel.panel-default
        .panel-heading role="tab" id="heading#{hyve.id}"
          .container
            .row.row-eq-height.vertical-align
              .col-xs-3.col-sm-3.col-md-3.col-lg-3.text-centered
                - if hyve.image.blank?
                  = image_tag "my_account/default.png", class: "my-hyve-image", id: "my-hyve-#{hyve.id}-image"
                - else
                  = image_tag "#{hyve.image_url}", class: "my-hyve-image", id: "my-hyve-#{hyve.id}-image"
              .col-xs-7.col-sm-7.col-md-7.col-lg-7.text-left
                h1 id="my-hyve-#{hyve.id}-header" #{hyve.name} 
              .col-xs-2.col-sm-2.col-md-2.col-lg-2.text-right
                h2
                  a aria-controls="collapse#{hyve.id}" aria-expanded="false" data-parent="" data-toggle="collapse" href="#collapse#{hyve.id}"
                    = image_tag "accordion/down.png", class: "accordion-down-arrow",id: "my-hyve-#{hyve.id}-arrow", html: { "aria-hidden" => "true" }

        .panel-collapse.collapse aria-labelledby="heading#{hyve.id}" role="tabpanel" id="collapse#{hyve.id}" 
          .panel-body
            .container id="my-hyve-#{hyve.id}-info"
              .row.row-eq-height
                .col-xs-12.col-sm-3.col-md-3.col-lg-3.vertical-align.center-align.text-centered
                  - if hyve.image.blank?
                    = image_tag "my_account/default.png", class: "my-hyve-image-large"
                  - else
                    = image_tag "#{hyve.image}", class: "my-hyve-image-large"
                .col-xs-12.col-sm-7.col-md-7.col-lg-7.text-left.vertical-align
                  table#hyve-info-details
                    col width="150"
                    col width="30"
                    col width="50"
                    col width="350"
                    tr
                      td colspan="4"
                        h1 #{hyve.name}
                    tr
                      td
                        label Distance
                      td
                        | :
                      td
                        = hyve.distance
                      td
                        | metres
                    tr
                      td
                        label Proximity 
                      td
                        | :
                      td.orange colspan="2"
                        - if hyve.proximity
                          = hyve.proximity
                        - else
                          p.no-margin Unknown
                    tr
                      td
                        label Registered Date
                      td
                        | :
                      td colspan="2"
                        = hyve.created_at
                    tr
                      td
                        label Last Connected
                      td
                        | :
                      td colspan="2"
                        = hyve.updated_at
                    tr
                      td
                        label UUID
                      td
                        | :
                      td colspan="2"
                        = hyve.uuid
                .col-xs-2.col-sm-2.col-md-2.col-lg-2.text-center.bottom-align.right-align
                  = link_to "Edit", "#edit-my-hyve-info", class: "btn btn-my-account-edit edit-my-hyve-info-btn", id: "edit-my-hyve-#{hyve.id}-info-btn", remote: true

            //hidden
            = render "my/accounts/edit_my_hyve_info", hyve: hyve

app/views/my/accounts/_my_user_info.html.slim
#my-user-info.container-fluid
  .row.row-eq-height.vertical-align
    .col-xs-12.col-sm-5.col-md-offset-2.col-md-3.col-lg-offset-2.col-lg-3.my-account-avatar-container
      - if @user.avatar.present?
        .my-account-avatar style="background-image: url(#{@user.avatar})"
      - else
        .my-account-avatar-default
    .col-xs-offset-2.col-xs-8.col-sm-offset-0.col-sm-4.col-md-offset-0.col-md-3.col-lg-offset-0.col-lg-3.white
      h4
        = @user.full_name.titleize
      p
        = @user.username
      p
        = @user.email
    .col-xs-offset-2.col-xs-8.col-sm-offset-0.col-sm-3.col-md-offset-0.col-md-2.col-lg-offset-0.col-lg-2.text-centered
      = link_to "Edit Profile", "#edit-my-account-info", class: "btn btn-my-account-edit", id: "edit-my-account-info-btn", remote: true

//hidden
= render "my/accounts/edit_my_user_info"

app/views/my/accounts/_user_info.html.slim
#user-info.container-fluid
  .row.row-eq-height.vertical-align
    .col-md-3.col-lg-3.my-account-avatar-container
      .my-account-avatar style="background-image: url(#{@user.avatar})"
    .col-md-6.col-lg-6.white
      h4
        = @user.full_name.titleize
      p
        = @user.username
      p
        = @user.email
    .col-md-3.col-lg-3.text-centered
      = link_to "Edit Profile", "#edit-my-account-info", class: "btn btn-edit-user-details", remote: true

app/views/my/accounts/show.html.slim
.container.text-centered
  = link_to "Log Out", logout_path, method: :post, class: "btn btn-my-account-edit"
= render "my/accounts/my_user_info"
= render "my/accounts/my_hyve_info"